server:
  port: 8090

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    url: jdbc:postgresql://115.190.94.44:15432/ai-rag-knowledge
    type: com.zaxxer.hikari.HikariDataSource
  ai:
    ollama:
      base-url: http://115.190.94.44:11434

# Redis
redis:
  sdk:
    config:
      host: 115.190.94.44
      port: 16379
      pool-size: 10
      min-idle-size: 5
      idle-timeout: 30000
      connect-timeout: 5000
      retry-attempts: 3
      retry-interval: 1000
      ping-interval: 60000
      keep-alive: true

logging:
  level:
    root: info
  config: classpath:logback-spring.xml
